name: workflow_1
on: workflow_dispatch
jobs:
  FIRST_JOB:
    runs-on: ubuntu-22.04
    steps:
      - name: print hello
        run: echo "hello world!!"
      - name: print goodbye
        run: echo "goodbye!!"
      - name: 
        run: ip a
      - run: whoami
